### ISSUE TITLE
Compatible with TYPO3 8.6 (and 8.7)?

### ISSUE THREAD

**Issue by mbrodala** [tdeuling/typo3-guide#5]
The current TYPO3 version is 8.6 and soon 8.7 will be released as LTS. This extension should be made/marked compatible with these.

**Comment by tdeuling** [comment]
Current master is 8.7 compatible. We're currently working on new features and real-life tours.
Next version will be released as soon as this work is done.

**Comment by mbrodala** [comment]
Thanks for the info, looking forward to that. :-)

**Comment by ghost** [comment]
If the next version isn't planned to be released within a few weeks, the it would be great if the current version could have a new release where the compatibility is raised to include TYPO3 8 LTS too :-)

**Comment by peterkraume** [comment]
See #8 for TYPO3 8.7.x Composer compatibilty.

**Comment by ghost** [comment]
Great. Will there also be a release to TER? It still says 1.1.0 at https://typo3.org/extensions/repository/view/guide :-(

**Comment by mbrodala** [comment]
Version 2.0.0 is available since September. 👍
